POST http://localhost:3500/ad
Content-Type: application/json

{
  "ads":
[
  {
  "title": "Switch",
  "description": "Switch red and blue....",
  "owner": "Emilie",
  "price": -150,
  "picture": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.phonandroid.com%2Fnintendo-switch-mario-rouge-bleu-acheter-meilleur-prix.html&psig=AOvVaw2phitV-moh9qTORSiCDaIw&ust=1695827096722000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCICora_GyIEDFQAAAAAdAAAAABAH",
  "location": "Jaunay-clan"
},
{ 
  "title": "VoitureMazda",
  "description": "Mazda Rouge",
  "owner": "Larry",
  "price": 15000,
  "picture": "https://www.ecosia.org/images?q=mazda%20rouge&addon=safari&addonversion=4.2.1.51#id=CAE8034B6B7B2EA738452C8456A8456172AD53EC",
  "location": "Paris" 
},
{ 
  "title": "Paris",
  "description": "Bleu",
  "owner": "Emilie",
  "price": 800,
  "picture": "https://www.ecosia.org/images?addon=safari&addonversion=4.2.1.51&q=iphone%2013%20bleu#id=88ADE6B120D91711DC2480C92CCAC74846060C5B",
  "location": "Bordeaux" 
},
{ 
  "title": "IpadPro",
  "description": "capacité 256GO",
  "owner": "Victoria",
  "price": 600,
  "picture": "https://www.ecosia.org/images?addon=safari&addonversion=4.2.1.51&q=ipad%20pro#id=E511A995403262A4908DCE680DC837F16FE894C3",
  "location": "Paris" 
},
{ 
  "title": "Spitz",
  "description": "Adulte de couleur noir",
  "owner": "Emilie",
  "price": 200,
  "picture": "https://www.ecosia.org/images?addon=safari&addonversion=4.2.1.51&q=spitz%20noir",
  "location": "Lyon" 
},
{ 
  "title": "Projecteur",
  "description": "de marque Samsung",
  "owner": "Larry",
  "price": 500,
  "picture": "https://www.iacono.fr/fr/20681-samsung-sp-lsp3blaxxe.html",
  "location": "Bordeaux" 
},
{ 
  "title": "Télé",
  "description": "18 pouces",
  "owner": "Larry",
  "price": 500,
  "picture": "https://www.ecosia.org/images?addon=safari&addonversion=4.2.1.51&q=télé",
  "location": "Lyon" 
},
{ 
  "title": "Chat",
  "description": "Famille de chat, don",
  "owner": "Larry",
  "price": 0,
  "picture": "https://www.ecosia.org/images?addon=safari&addonversion=4.2.1.51&q=chat",
  "location": "Poitiers" 
},
{ 
  "title": "EcouteursAirpods",
  "description": "Neuve modèle pro",
  "owner": "Larry",
  "price": 400,
  "picture": "https://www.ecosia.org/images?addon=safari&addonversion=4.2.1.51&q=airpod%20pro",
  "location": "Bordeaux" 
},
{ 
  "title": "maisonF4",
  "description": "Maison de campagne  F4",
  "owner": "Larry",
  "price": 400000,
  "picture": "https://www.ecosia.org/images?addon=safari&addonversion=4.2.1.51&q=Maison%20F4",
  "location": "Guadeloupe" 
},
{ 
  "title": "Casquebeats",
  "description": "Edition Mickey",
  "owner": "Victoria",
  "price": 300,
  "picture": "https://www.ecosia.org/images?addon=safari&addonversion=4.2.1.51&q=casque%20beats%20mickey",
  "location": "Japon" 
}
]
}