POST http://localhost:3500/ad
Content-Type: application/json

{
  
  "title": "Switch",
  "description": "Switch red and blue....",
  "owner": "Emilie",
  "price": -150,
  "picture": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.phonandroid.com%2Fnintendo-switch-mario-rouge-bleu-acheter-meilleur-prix.html&psig=AOvVaw2phitV-moh9qTORSiCDaIw&ust=1695827096722000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCICora_GyIEDFQAAAAAdAAAAABAH",
  "location": "Jaunay-clan",
  "category": 1,
  "tags": [{"id":1}, {"id":2}, {"name": "tag4"}]

}